### ISSUE TITLE
Feature: Implement implicit cast from struct to map

### ISSUE THREAD

**Issue by Brad-Edwards** [KeplerOps/kuzu#257]
Imported from `kuzudb/kuzu#3985`
Original URL: https://github.com/kuzudb/kuzu/issues/3985
Original author: @acquamarin
Original created at: 2024-07-30T13:40:51Z
### API

Python

### Description

Users may want to provide a struct (e.g., a Python dict) as a node property. This currently fails with an implicit casting error.

```py
import shutil
import kuzu

shutil.rmtree("test_db", ignore_errors=True)
db = kuzu.Database("test_db")
conn = kuzu.Connection(db)

conn.execute(
    """
    CREATE NODE TABLE Student (
        name STRING,
        grades MAP(STRING, INT64),
        PRIMARY KEY(name)
    )
    """
)

conn.execute(
    """
    CREATE (a:Student {name: "Karissa"})
        SET a.grades = {"math": 92, "physics": 91, "music": 78};
    CREATE (b:Student {name: "Adam"})
        SET b.grades = {"history": 81, "english": 87}
    """
)

res = conn.execute("MATCH (p:Person) RETURN p.name, p.grades")
while res.has_next():
    result = res.get_next()
    print(result)
```
Currently throws an exception since we don't support implicit cast from `struct`->`map`

This is the exception:
```
Traceback (most recent call last):
  File "/code/kuzu/test.py", line 21, in <module>
    conn.execute(
  File "/code/kuzu/tools/python_api/build/kuzu/connection.py", line 130, in execute
    _query_result = self._connection.query(query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Binder exception: Expression STRUCT_PACK(math,physics,music) has data type STRUCT(math INT64, physics INT64, music INT64) but expected MAP(STRING, INT64). Implicit cast is not supported.
```

**Comment by Brad-Edwards** [comment]
Imported comment from `kuzudb/kuzu`
Original author: @Tauvic
Original created at: 2025-01-20T14:42:46Z
Original URL: https://github.com/kuzudb/kuzu/issues/3985#issuecomment-2602602675
Almost the same problem.

    conn.execute("CREATE NODE TABLE Page(url STRING PRIMARY KEY, \
                                         title STRING, \
                                         created TIMESTAMP DEFAULT current_timestamp(), \
                                         modified TIMESTAMP DEFAULT current_timestamp())")
    
    conn.execute("CREATE NODE TABLE Element(sid SERIAL PRIMARY KEY, \
                                       tag STRING, \
                                       id STRING,  \
                                       attributes MAP(STRING,STRING[]))")

    conn.execute("CREATE REL TABLE GROUP hasParent(FROM Element TO Element, FROM Element TO Page, MANY_ONE)")

    url = "https://homepage.com"
    title = "WebShop"
    conn.execute("CREATE (n:Page {url: $url,title:$title})",
                  parameters={"url":url,"title":title})

    tag = "head"
    attributes= {'class': ['a'], 'name': ['b']}
    rs = conn.execute("CREATE (n:Element {tag: $tag, attributes:$attr})",
                      parameters={"tag":tag,"attr":attributes})    
    
RuntimeError: Binder exception: Expression $attr has data type STRUCT(class STRING[], name STRING[]) but expected MAP(STRING, STRING[]). Implicit cast is not supported.
